---
version: "2.4"

services:
  sut:
    image: golang:1.23.5
    volumes:
      - .:/go/src/github.com/balena-io/sshproxy
    working_dir: /go/src/github.com/balena-io/sshproxy
    entrypoint:
      - /bin/bash
      - "-c"
    command:
      - |
        set -axe

        git config --global --add safe.directory $(pwd)

        make -j $$(nproc) clean dep lint test
